language: node_js
addons:
  apt:
    packages:
    - rabbitmq-server 
services: 
  - mongodb
  - docker
  - rabbitmq
node_js:
  - "12"
after_success:
  - npm run lint
  - npm build
  - npm test
  - docker build . -t dbplay/mplay-runner 
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
