language: node_js
services: 
  - mongodb
  - docker
node_js:
  - "12"
after_success:
  - npm run lint
  - npm build
  - npm test
  - docker build . -t mplay-runner 
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
